name: go-unit-test
on: [push]
jobs:
  go-unit-test:
    runs-on: ubuntu-21.10
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      - 
        name: Go test
        run: go test ./...
